# Generated by Django 6.0.1 on 2026-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='user/')),
                ('gmail', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
